source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
project '/Users/swift/Documents/Senior Project/HappyGrading/HappyGrading.xcodeproj’
use_frameworks!

target ‘HappyGrading’ do
pod 'Alamofire', '~> 4.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
end
